default_platform(:ios)

platform :ios do
  desc "Run MyAppTests with scan"
  lane :my_app_tests do
    scan(
      project: "MyProject.xcodeproj",
      scheme: "MyApp",
      # xcodebuild_formatter: "xcbeautify",
      xcodebuild_formatter: "xcpretty",
      clean: true,
      skip_build: false,
      build_for_testing: true
    )
  end
end
